devices = ["Shenzhen ViewAt Technology Co.,Ltd. ",
"Integrated Device Technology (Malaysia) Sdn. Bhd.",
"NETGEAR",
"Hewlett Packard",
"Hewlett Packard",
"Hewlett Packard",
"Hewlett Packard",
"Cognitec Systems GmbH",
"D-Link Corporation",
"D-Link Corporation",
"D-Link International",
"D-Link International",
"D-Link International",
"D-Link International",
"D-Link International",
"Sagemcom Broadband SAS",
"Sagemcom Broadband SAS",
"Sagemcom Broadband SAS",
"DGS Denmark A/S",
"COL GIOVANNI PAOLO SpA",
"CTR SRL",
"Sagemcom Broadband SAS",
"SHENZHEN CHUANGWEI-RGB ELECTRONICS CO.,LTD",
"Private",
"Aerohive Networks Inc.",
"ServerNet S.r.l.",
"Cisco Systems, Inc",
"HUAWEI TECHNOLOGIES CO.,LTD",
"HUAWEI TECHNOLOGIES CO.,LTD",
"HUAWEI TECHNOLOGIES CO.,LTD",
"HUAWEI TECHNOLOGIES CO.,LTD",
"HUAWEI TECHNOLOGIES CO.,LTD",
"Apple, Inc.",
"Microsoft Mobile Oy",
"Cisco Systems, Inc",
"Chicony Electronics Co., Ltd.",
"SourcingOverseas Co. Ltd",
"HTC Corporation",
"Jide Technology (Hong Kong) Limited",
"Google, Inc.",
"Google, Inc.",
"Shenzhen TINNO Mobile Technology Corp.",
"Qiku Internet Network Scientific (Shenzhen) Co., Ltd.",
"Apple, Inc.",
"SHENZHEN CHUANGWEI-RGB ELECTRONICS CO.,LTD",
"Intel Corporation",
"Intel Corporation",
"Intel Corporate",
"Intel Corporate",
"Intel Corporate",
"Intel Corporate",
"Intel Corporate",
"BUFFALO.INC",
"BUFFALO.INC",
"BUFFALO.INC",
"BUFFALO.INC",
"Hewlett Packard",
"Hewlett Packard",
"Hewlett Packard",
"Hewlett Packard",
"Hewlett Packard",
"Hewlett Packard",
"Hewlett Packard",
"Hewlett Packard",
"Hewlett Packard",
"Hewlett Packard",
"Hewlett Packard",
"Hewlett Packard",
"HTC Corporation",
"zte corporation",
"HUAWEI TECHNOLOGIES CO.,LTD",
"HUAWEI TECHNOLOGIES CO.,LTD",
"HUAWEI TECHNOLOGIES CO.,LTD",
"HUAWEI TECHNOLOGIES CO.,LTD",
"HUAWEI TECHNOLOGIES CO.,LTD",
"HUAWEI TECHNOLOGIES CO.,LTD",
"HUAWEI TECHNOLOGIES CO.,LTD",
"HUAWEI TECHNOLOGIES CO.,LTD",
"HUAWEI TECHNOLOGIES CO.,LTD",
"HUAWEI TECHNOLOGIES CO.,LTD",
"HUAWEI TECHNOLOGIES CO.,LTD",
"HUAWEI TECHNOLOGIES CO.,LTD",
"HUAWEI TECHNOLOGIES CO.,LTD",
"GUANGDONG OPPO MOBILE TELECOMMUNICATIONS CORP.,LTD",
"GUANGDONG OPPO MOBILE TELECOMMUNICATIONS CORP.,LTD",
"Murata Manufacturing Co., Ltd.",
"Murata Manufacturing Co., Ltd.",
"Hitron Technologies. Inc",
"Brocade Communications Systems, Inc.",
"Brocade Communications Systems, Inc.",
"Brocade Communications Systems, Inc.",
"zte corporation",
"zte corporation",
"TP-LINK TECHNOLOGIES CO.,LTD.",
"TP-LINK TECHNOLOGIES CO.,LTD.",
"TP-LINK TECHNOLOGIES CO.,LTD.",
"TP-LINK TECHNOLOGIES CO.,LTD.",
"TP-LINK TECHNOLOGIES CO.,LTD.",
"TP-LINK TECHNOLOGIES CO.,LTD.",
"TP-LINK TECHNOLOGIES CO.,LTD.",
"TP-LINK TECHNOLOGIES CO.,LTD.",
"TP-LINK TECHNOLOGIES CO.,LTD.",
"HUAWEI TECHNOLOGIES CO.,LTD",
"Cochlear Limited",
"Sysorex Global Holdings",
"Apple, Inc.",
"Apple, Inc.",
"HUAWEI TECHNOLOGIES CO.,LTD",
"HUAWEI TECHNOLOGIES CO.,LTD",
"HUAWEI TECHNOLOGIES CO.,LTD",
"Hewlett Packard",
"Hewlett Packard",
"Hewlett Packard",
"Hewlett Packard",
"Hewlett Packard",
"Hewlett Packard",
"Hewlett Packard",
"Hewlett Packard",
"Hewlett Packard",
"Hewlett Packard",
"Hewlett Packard",
"Hewlett Packard",
"Hewlett Packard",
"Hewlett Packard",
"Hewlett Packard",
"Rain Bird Corporation",
"HTC Corporation",
"Cisco-Linksys, LLC",
"Cisco-Linksys, LLC",
"Cisco-Linksys, LLC",
"Cisco SPVTG",
"Cisco SPVTG",
"Cisco SPVTG",
"Cisco SPVTG",
"Cisco SPVTG",
"ALPS ELECTRIC CO.,LTD.",
"ALPS ELECTRIC CO.,LTD.",
"Shanghai Feixun Communication Co.,Ltd.",
"HUAWEI TECHNOLOGIES CO.,LTD",
"HUAWEI TECHNOLOGIES CO.,LTD",
"HUAWEI TECHNOLOGIES CO.,LTD",
"HUAWEI TECHNOLOGIES CO.,LTD",
"HUAWEI TECHNOLOGIES CO.,LTD",
"HUAWEI TECHNOLOGIES CO.,LTD",
"HUAWEI TECHNOLOGIES CO.,LTD",
"HUAWEI TECHNOLOGIES CO.,LTD",
"HUAWEI TECHNOLOGIES CO.,LTD",
"HUAWEI TECHNOLOGIES CO.,LTD",
"HUAWEI TECHNOLOGIES CO.,LTD",
"HUAWEI TECHNOLOGIES CO.,LTD",
"Xiaomi Communications Co Ltd",
"Xiaomi Communications Co Ltd",
"Xiaomi Communications Co Ltd",
"Xiaomi Communications Co Ltd",
"Xiaomi Communications Co Ltd",
"Xiaomi Communications Co Ltd",
"Comark Interactive Solutions",
"Cisco Systems, Inc",
"Cisco Systems, Inc",
"Cisco Systems, Inc",
"Cisco Systems, Inc",
"ASUSTek COMPUTER INC.",
"ASUSTek COMPUTER INC.",
"ASUSTek COMPUTER INC.",
"ASUSTek COMPUTER INC.",
"ASUSTek COMPUTER INC.",
"ASUSTek COMPUTER INC.",
"ASUSTek COMPUTER INC.",
"ShenZhen Protruly Electronic Ltd co.",
"Cisco Systems, Inc",
"Cisco Systems, Inc",
"HUAWEI TECHNOLOGIES CO.,LTD",
"HUAWEI TECHNOLOGIES CO.,LTD",
"HUAWEI TECHNOLOGIES CO.,LTD",
"HUAWEI TECHNOLOGIES CO.,LTD",
"Avaya Inc",
"Avaya Inc",
"Avaya Inc",
"Avaya Inc",
"Avaya Inc",
"Avaya Inc",
"Avaya Inc",
"Avaya Inc",
"Cisco Systems, Inc",
"Cisco Systems, Inc",
"Cisco Systems, Inc",
"Cisco Systems, Inc",
"Cisco Systems, Inc",
"Cisco Systems, Inc",
"Cisco Systems, Inc",
"Cisco Systems, Inc",
"Cisco Systems, Inc",
"Cisco Systems, Inc",
"Cisco Systems, Inc",
"Cisco Systems, Inc",
"Cisco SPVTG",
"Cisco SPVTG",
"Cisco Systems, Inc",
"Cisco Systems, Inc",
"Cisco Systems, Inc",
"Cisco Systems, Inc",
"Cisco Systems, Inc",
"Cisco Systems, Inc",
"Cisco Systems, Inc",
"Cisco Systems, Inc",
"Cisco Systems, Inc",
"Cisco Systems, Inc",
"Cisco Systems, Inc",
"Cisco Systems, Inc",
"Cisco Systems, Inc",
"Cisco Systems, Inc",
"Cisco Systems, Inc",
"Cisco Systems, Inc",
"Cisco Systems, Inc",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Saffron Solutions Inc",
"Intellisis",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"ASUSTek COMPUTER INC.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Cisco Systems, Inc",
"Cisco Systems, Inc",
"Cisco Systems, Inc",
"Cisco Systems, Inc",
"Cisco Systems, Inc",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"Apple, Inc.",
"ATP Electronics, Inc.",
"Cisco SPVTG",
"TRENDnet, Inc.",
"Toshiba",
"Zhejiang Everbright Communication Equip. Co,. Ltd",
"JinQianMao  Technology Co.,Ltd.",
"OVH",
"Linctronix Ltd,",
"Charles River Laboratories",
"Hangzhou Xueji Technology Co., Ltd.",
"Fiberhome Telecommunication Technologies Co.,LTD",
"Poynt Co.",
"Beijing Infosec Technologies Co., LTD.",
"GOPEACE Inc.",
"Source Chain",
"Viptela, Inc",
"SHENZHEN MERCURY COMMUNICATION TECHNOLOGIES CO.,LTD.",
"Shanghai DareGlobal Technologies Co.,Ltd",
"Private",
"Acoustic Stream",
"Control Solutions LLC",
"iPort",
"G24 Power Limited",
"HUAWEI TECHNOLOGIES CO.,LTD",
"Goyoo Networks Inc.",
"Mciao Technologies, Inc.",
"KYOCERA Corporation",
"Shenzhen Ferex Electrical Co.,Ltd",
"HangZhou KuoHeng Technology Co.,ltd",
"Beijing Guang Runtong Technology Development Company co.,Ltd",
"ABB Global Industries and Services Private Limited",
"Shenzhen Prifox Innovation Technology Co., Ltd.",
"Parallel Wireless, Inc",
"Polyera",
"Private",
"NEC Platforms, Ltd.",
"ROXTON Ltd.",
"Apple, Inc.",
"Husqvarna AB",
"AzureWave Technology Inc.",
"HUAWEI TECHNOLOGIES CO.,LTD",
"Gemtek Technology Co., Ltd.",
"HUAWEI TECHNOLOGIES CO.,LTD",
"Davit Solution co.",
"Jiangxi Hongpai Technology Co., Ltd.",
"Shanghai Baud Data Communication Co.,Ltd.",
"Private",
"Lupine Lighting Systems GmbH",
"P2 Mobile Technologies Limited",
"HUAWEI TECHNOLOGIES CO.,LTD",
"Atomic Rules LLC",
"Qolsys Inc.",
"Fiberhome Telecommunication Technologies Co.,LTD",
"Junilab, Inc.",
"ShengHai Electronics (Shenzhen) Ltd",
"ECHOSENS",
"innodisk Corporation",
"Routerboard.com",
"Qingdao Eastsoft Communication Technology Co.,LTD",
"Vodafone Omnitel B.V.",
"Network Instruments",
"MITSUMI ELECTRIC CO.,LTD.",
"Microsoft Corporation",
"Oilfind International LLC",
"Weifang GoerTek Electronics Co., Ltd.",
"Cambrionix Ltd",
"HUAWEI TECHNOLOGIES CO.,LTD",
"Beijing SHENQI Technology Co., Ltd.",
"Bosung Electronics Co., Ltd.",
"Philips Oral Healthcare, Inc.",
"Suzhou Torchstar Intelligent Technology Co.,Ltd",
"MEDIA GLOBAL LINKS CO., LTD.",
"LAVA INTERNATIONAL(H.K) LIMITED",
"Mercedes-Benz USA, LLC",
"Chuango Security Technology Corporation",
"HUAWEI TECHNOLOGIES CO.,LTD",
"Liteon, Inc.",
"Invensys Controls UK Limited",
"LG Innotek",
"Electrocompaniet A.S.",
"Cambridge Mobile Telematics, Inc.",
"Esan electronic co.",
"ITTIM Technologies",
"Acacia Communications",
"EMC",
"ZTLX Network Technology Co.,Ltd",
"SB SYSTEMS Co.,Ltd",
"King Slide Technology CO., LTD.",
"Aquantia Corporation",
"Letv Mobile and Intelligent Information Technology (Beijing) Corporation Ltd.",
"OMRON HEALTHCARE Co., Ltd.",
"Sony Mobile Communications AB",
"Leading Public Performance Co., Ltd.",
"TangoWiFi.com",
"Private",
"ELECOM CO.,LTD.",
"SHENZHEN MERCURY COMMUNICATION TECHNOLOGIES CO.,LTD.",
"zte corporation",
"Shenzhen Primestone Network Technologies.Co., Ltd.",
"Biosoundlab Co., Ltd.",
"Mist Systems, Inc.",
"SHENZHEN BOOMTECH INDUSTRY CO.,LTD",
"IDEO Security Co., Ltd.",
"zte corporation",
"Private",
"Avotek corporation",
"Microsoft Corporation",
"HUIZHOU MAORONG INTELLIGENT TECHNOLOGY CO.,LTD",
"KEISOKUKI CENTER CO.,LTD.",
"Minxon Hotel Technology INC.",
"WiFiSong",
"Sino-Telecom Technology Co.,Ltd.",
"Shenzhen Gongjin Electronics Co.,Ltd",
"Davit System Technology Co., Ltd.",
"TOP-ACCESS ELECTRONICS CO LTD",
"Vital Connect, Inc.",
"NET RULES TECNOLOGIA EIRELI",
"INNO S",
"SHENZHEN FAST TECHNOLOGIES CO.,LTD",
"Shenzhen Yourf Kwan Industrial Co., Ltd",
"Shenzhen UTEPO Tech Co., Ltd.",
"Tallac Networks",
"Shanghai Reallytek Information Technology  Co.,Ltd",
"DriveScale, Inc.",
"Seeed Technology Inc.",
"Yaojin Technology(Shenzhen)Co.,Ltd",
"Beijing Autelan Technology Co.,Ltd",
"Nanomegas",
"Maike Industry(Shenzhen)CO.,LTD",
"ATN International Limited",
"SHEN ZHEN HENG SHENG HUI DIGITAL TECHNOLOGY CO.,LTD",
"Koubachi AG",
"Extreme Networks",
"Loxley Public Company Limited",
"Reacheng Communication Technology Co.,Ltd",
"Micro-Star INTL CO., LTD.",
"Systech Electronics Ltd.",
"Microsoft Corporation",
"ShangHai sunup lighting CO.,LTD",
"SHENZHEN MERCURY COMMUNICATION TECHNOLOGIES CO.,LTD.",
"Top Victory Electronics (Taiwan) Co., Ltd.",
"Rosslare Enterprises Limited",
"Greenvity Communications",
"Yangzhou ChangLian Network Technology Co,ltd.",
"Shenzhen RF Technology Co., Ltd",
"Vuzix / Lenovo",
"Panasonic Taiwan Co.,Ltd.",
"Step forward Group Co., Ltd.",
"KMB systems, s.r.o.",
"Murata Manufacturing Co., Ltd.",
"Sonos, Inc.",
"NEC Corporation",
"D-Link International",
"Ruckus Wireless",
"Vubiq Networks, Inc.",
"Neterix",
"DirectPacket Research, Inc,",
"SHENZHEN SPACETEK TECHNOLOGY CO.,LTD",
"Hitachi Maxell, Ltd., Optronics Division",
"Four systems Co.,Ltd.",
"Fike Corporation",
"INDUSTRIAS UNIDAS SA DE CV",
"Liling FullRiver Electronics & Technology Ltd",
"ASUSTek COMPUTER INC.",
"Cisco SPVTG",
"Microsoft Corporation",
"ruwido austria gmbh",
"Rigado, LLC",
"Guangzhou Younghead Electronic Technology Co.,Ltd",
"AIRTAME ApS",
"DONGGUAN HELE ELECTRONICS CO., LTD",
"CloudBerry Technologies Private Limited",
"Nishiyama Industry Co.,LTD.",
"Shenzhen Guzidi Technology Co.,Ltd",
"Electronics Company Limited",
"D-Link International",
"Fujian Great Power PLC Equipment Co.,Ltd",
"Prophet Electronic Technology Corp.,Ltd",
"Thread Technology Co., Ltd",
"Silca Spa",
"chaowifi.com",
"Scientech Materials Corporation",
"Skyport Systems",
"zte corporation",
"Suzhou HOTEK  Video Technology Co. Ltd",
"IMS Messsysteme GmbH",
"Zioncom Electronics (Shenzhen) Ltd.",
"TP-LINK TECHNOLOGIES CO.,LTD.",
"Shenzhen Jin Yun Video Equipment Co., Ltd.",
"Alcatel-Lucent",
"COMPAL INFORMATION (KUNSHAN) CO., LTD.",
"MMPC Inc.",
"iRule LLC",
"Beijing Huafei Technology Co., Ltd.",
"TAKT Corporation",
"Yokogawa Digital Computer Corporation",
"Bluebank Communication Technology Co.Ltd",
"Maxwell Forest",
"Shenzhen Linghangyuan Digital Technology Co.,Ltd.",
"Ruckus Wireless",
"Aitexin Technology Co., Ltd",
"Dalian Netmoon Tech Develop Co.,Ltd",
"samtec automotive electronics & software GmbH",
"Shenzhen Xin KingBrand enterprises Co.,Ltd",
"Welgate Co., Ltd.",
"shenzhen yunmao information technologies co., ltd",
"GatesAir, Inc",
"Technische Alternative GmbH",
"Newbridge Technologies Int. Ltd.",
"MEXUS CO.,LTD",
"Wisol",
"SkyDisk, Inc.",
"Zhejiang Hite Renewable Energy Co.,LTD",
"SIFROM Inc.",
"Shenzhen Linkworld Technology Co,.LTD",
"New Singularity International Technical Development Co.,Ltd",
"Ilshin Elecom",
"Penguin Computing",
"Stage One International Co., Ltd.",
"zte corporation",
"HiTEM Engineering",
"Ciena Corporation",
"OOO NPP Systemotechnika-NN",
"Wistron InfoComm(Kunshan)Co.,Ltd.",
"Custom Control Concepts",
"Suzhou Chi-tek information technology Co., Ltd",
"Castlenet Technology Inc.",
"Automatic Bar Controls Inc.",
"Aerohive Networks Inc.",
"Bointec Taiwan Corporation Limited",
"Ruckus Wireless",
"Nokia Corporation",
"TP-LINK TECHNOLOGIES CO.,LTD.",
"Sercomm Corporation",
"Research Centre Module",
"Huizhou Super Electron Technology Co.,Ltd.",
"AXPRO Technology Inc.",
"MIC Technology Group",
"NietZsche enterprise Co.Ltd.",
"AHN INC.",
"EQUES Technology Co., Limited",
"EnvyLogic Co.,Ltd.",
"Impex-Sat GmbH&amp;Co KG",
"Experimental Factory of Scientific Engineering and Special Design Department",
"Optek Digital Technology company limited",
"Pep Digital Technology (Guangzhou) Co., Ltd",
"Telegartner Karl Gartner GmbH",
"Hyundai ESG",
"Nokia Corporation",
"Weifang GoerTek Electronics Co., Ltd",
"R L Drake",
"D-Link International",
"MAX-TECH,INC",
"ShenZhen Rapoo Technology Co., Ltd.",
"HTC Corporation",
"Siemens Low Voltage & Products",
"eZEX corporation",
"EUMTECH CO., LTD",
"Huami Information Technology Co.,Ltd.",
"Private",
"tado GmbH",
"Technicolor",
"GUANGDONG TONZE ELECTRIC CO.,LTD",
"Westunitis Co., Ltd.",
"ESSYS",
"PowerComm Solutions LLC",
"Toy's Myth Inc.",
"BALMUDA Inc.",
"Canopus Systems US LLC",
"mywerk system GmbH",
"Trend Electronics Co., Ltd.",
"Atomax Inc.",
"Kirisun Communications Co., Ltd.",
"GreenPriz",
"AKG Acoustics GmbH",
"H.K ZONGMU TECHNOLOGY CO., LTD.",
"Hitron Technologies. Inc",
"Routerboard.com",
"shenzhen eyunmei technology co,.ltd",
"Swisscom Energy Solutions AG",
"ACTP, Inc.",
"Viscount Systems Inc.",
"Alphion India Private Limited",
"MTN Electronic Co. Ltd",
"SUNGSAM CO,.Ltd",
"OTEC(Shanghai)Technology Co.,Ltd.",
"Jenny Science AG",
"ADATA Technology Co., Ltd",
"INTERSENSOR S.R.L.",
"GMJ ELECTRIC LIMITED",
"SHENZHEN TW-SCIE Co., Ltd",
"Neets",
"Luxshare Precision Industry Co.,Ltd.",
"SAM Electronics GmbH",
"WaveIP",
"Emerson Climate Technologies Transportation Solutions",
"Pishion International Co. Ltd",
"TP-LINK TECHNOLOGIES CO.,LTD.",
"aFUN TECHNOLOGY INC.",
"Shenzhen Hualistone Technology Co.,Ltd",
"Shenzhen Linsn Technology Development Co.,Ltd",
"Beijing Winchannel Software Technology Co., Ltd",
"COMPAL INFORMATION (KUNSHAN) CO., LTD.",
"Kodofon JSC",
"Pintsch Tiefenbach GmbH",
"Telefonbau Behnke GmbH",
"ThinGlobal LLC",
"Unikey Technologies",
"Actiontec Electronics, Inc",
"Filmetrics Inc.",
"IBC TECHNOLOGIES INC.",
"Mita-Teknik A/S",
"Helmer Scientific",
"Contec GmbH",
"Syscor Controls &amp; Automation",
"Onyx Healthcare Inc.",
"Sony Mobile Communications AB",
"Addrek Smart Solutions",
"MIDORI ELECTRONIC CO., LTD.",
"General Electric Water & Process Technologies",
"Shenzhen Strong Rising Electronics Co.,Ltd DongGuan Subsidiary",
"Codetek Technology Co.,Ltd",
"Budelmann Elektronik GmbH",
"Sunbow Telecom Co., Ltd.",
"Voxtronic Technology Computer-Systeme GmbH",
"EDP Servicos",
"Nokia Corporation",
"Advantage Pharmacy Services, LLC",
"iDevices, LLC",
"Gionee Communication Equipment Co,Ltd.ShenZhen",
"Pacidal Corporation Ltd.",
"CZ.NIC, z.s.p.o.",
"Private",
"ELNO",
"Lenovo Mobile Communication Technology Ltd.",
"Actineon",
"UTStarcom (China) Co.,Ltd",
"Jolla Ltd",
"LINKCOM",
"WISEWARE, Lda",
"D-Link International",
"ETEK TECHNOLOGY (SHENZHEN) CO.,LTD",
"zte corporation",
"Adaptrum Inc.",
"SPECTO PAINEIS ELETRONICOS LTDA",
"Sony Mobile Communications AB",
"Shenzhen Gongjin Electronics Co.,Ltd",
"Discovery Technology,LTD..",
"YAZAKI Energy System Corporation",
"Huike Electronics (SHENZHEN) CO., LTD.",
"WING SING ELECTRONICS HONG KONG LIMITED",
"CHOFU SEISAKUSHO CO.,LTD",
"ESEN Optoelectronics Technology Co.,Ltd.",
"Intercon Systems Co., Ltd.",
"Spazio Italia srl",
"M-Cube Spa",
"Montage Technology Group Limited",
"zte corporation",
"Host Mobility AB",
"Micro-Biz intelligence solutions Co.,Ltd",
"MindMade Sp. z o.o.",
"Applied Vision Corporation",
"AE REFUsol",
"Shenzhen Coship Electronics Co., Ltd.",
"Samhwa Telecom",
"Optowiz Co., Ltd",
"abatec group AG",
"Pantech Co., Ltd.",
"littleBits Electronics, Inc.",
"TECHNART Co.,Ltd",
"Westcontrol AS",
"Innometriks Inc",
"TPL SYSTEMES",
"Shanghai Magic Mobile Telecommunication Co.Ltd.",
"TESCOM CO., LTD.",
"PROSYST",
"Terewave. Inc.",
"Zhejiang shenghui lighting co.,Ltd",
"Lenovo Mobile Communication Technology Ltd.",
"SAMJIN Co., Ltd.",
"SK hynix",
"MCS Logic Inc.",
"KAESER KOMPRESSOREN AG",
"ThinPAD Technology (Shenzhen)CO.,LTD",
"Bluwan SA",
"CommSky Technologies",
"Inventek Systems",
"Beijing BenyWave Technology Co., Ltd.",
"Opticon Sensors Europe B.V.",
"Sunwave Communications Co., Ltd",
"Vispiron Rotec GmbH",
"Advantage Controls",
"Ruckus Wireless",
"Shenzhen Xiaoniao Technology Co.,Ltd",
"SkyHawke Technologies, LLC.",
"Laser Light Engines",
"Qualisys AB",
"Shenzhen Vsun communication technology Co.,ltd",
"APS systems/electronic AG",
"BODi rS, LLC",
"Nanjing CAS-ZDC IOT SYSTEM CO.,LTD",
"Hangzhou Sunyard Technology Co., Ltd.",
"KYOCERA Display Corporation",
"Aclima, Inc.",
"Physio-Control, Inc",
"Affinegy",
"Jiangsu Switter Co., Ltd",
"2Wire Inc",
"Wistron (ChongQing)",
"Lokel s.r.o.",
"Car Connectivity Consortium",
"Shanghai Guao Electronic Technology Co., Ltd",
"Creatcomm Technology Inc.",
"ShenZhen Cando Electronics Co.,Ltd",
"In Home Displays Ltd",
"Sichuan Bihong Broadcast &amp; Television New Technologies Co.,Ltd",
"Southwest Microwave, Inc",
"Penetek, Inc",
"D-Link International",
"Denwa Technology Corp.",
"Hanvit SI, Inc.",
"APATOR S.A.",
"U&U ENGINEERING INC.",
"HTC Corporation",
"Innokas Group",
"UPVEL",
"Indu-Sol GmbH",
"YODO Technology Corp. Ltd.",
"Leopold Kostal GmbH &Co. KG",
"DAE EUN ELETRONICS CO., LTD",
"Raycore Taiwan Co., LTD.",
"WindowMaster A/S",
"Beijing HCHCOM Technology Co., Ltd",
"Velex s.r.l.",
"Private",
"KERNEL-I Co.,LTD",
"Heinzmann GmbH & CO. KG",
"TP-LINK TECHNOLOGIES CO.,LTD.",
"Logic3 plc",
"NanJing Chaoran Science & Technology Co.,Ltd.",
"ERECA",
"FONsystem co. ltd.",
"AREC Inc.",
"ISC applied systems corp",
"Technicolor",
"MTMCommunications",
"Airo Wireless",
"Samsung Semiconductor Inc.",
"Advantage Electronics",
"Metro Ethernet Forum",
"GreenBytes, Inc.",
"Ubizcore Co.,LTD",
"Beijing Symtech CO.,LTD",
"Meraki, Inc.",
"MACANDC",
"V. Stonkaus firma Kodinis Raktas",
"Smartek d.o.o.",
"Masimo Corporation",
"RTW GmbH & Co. KG",
"ASUSTek COMPUTER INC.",
"Shenzhen Yichen Technology Development Co.,LTD",
"China SSJ (Suzhou) Network Technology Inc.",
"SHOWA DENKI CO.,LTD.",
"AG Elektronik AB",
"IMAGO Technologies GmbH",
"Fujian Sanao Technology Co.,Ltd",
"Microstep-MIS spol. s r.o.",
"FUJITSU LIMITED",
"BLU CASTLE S.A.",
"Grandex International Corporation",
"MVTECH co., Ltd",
"Shanghai Chint Power Systems Co., Ltd.",
"Hanyang Digitech Co.Ltd",
"IEEE 1904.1 Working Group",
"Shenzhen Geniatech Inc, Ltd",
"Masterwork Automodules",
"ATH system",
"Loxone Electronics GmbH",
"FLOW DATA INC",
"DarbeeVision Inc.",
"Corsair Components",
"Amicus SK, s.r.o.",
"FASTWEL INTERNATIONAL CO., LTD. Taiwan Branch",
"zte corporation",
"Starkey Labs Inc.",
"Synaptics, Inc",
"Fibar Group sp. z o.o.",
"Q9 Networks Inc.",
"FiveCo",
"cozybit, Inc.",
"Cisco SPVTG",
"Guangzhou Robustel Technologies Co., Limited",
"Cameo Communications, Inc.",
"Out of the Fog Research LLC",
"FLAT DISPLAY TECHNOLOGY CORPORATION",
"Mobileeco Co., Ltd",
"IoT Tech Limited",
"Ubiquitous Communication Co. ltd.",
"ITG, Inc.",
"Ad-Sol Nissin Corp",
"Comprehensive Power",
"CANON INC.",
"Albedo Telecom SL",
"AgJunction",
"SysMik GmbH Dresden",
"Cisco SPVTG",
"Acro Associates, Inc.",
"NOBLEX SA",
"MileSight Technology Co., Ltd.",
"SCSpro Co.,Ltd",
"Cisco SPVTG",
"Qingdao Santong Digital Technology Co.Ltd",
"VisionVera International Co., Ltd.",
"Futaba-Kikaku",
"Newland Design + Assoc. Inc.",
"Cisco Systems, Inc",
"Villiger Security Solutions AG",
"plugg srl",
"Lufkin Industries",
"SMC Networks Inc",
"Ruckus Wireless",
"Wi-Fi Alliance",
"World Elite Technology Co.,LTD",
"EWM Hightec Welding GmbH",
"Simon-Kaloi Engineering",
"SAMBON PRECISON and ELECTRONICS",
"DONG OH PRECISION CO., LTD. ",
"Elsys Equipamentos Eletronicos Ltda",
"Advance Vision Electronics Co. Ltd.",
"ATCOM Technology Co.Ltd.",
"GERP Solution",
"Gerhard D. Wempe KG",
"zte corporation",
"SOREEL",
"KangSheng LTD.",
"Kessler Crane Inc.",
"SilverPlus, Inc",
"PowerCloud Systems, Inc.",
"Adaptive Wireless Solutions, LLC",
"AES Corporation",
"EDIC Systems Inc.",
"DeviceDesign",
"Axion Technologies Inc.",
"Conti Temic Microelectronic GmbH",
"PLATH GmbH",
"Shanghai Uniscope Technologies Co.,Ltd",
"Wonderlan (Beijing) Technology Co., Ltd.",
"Plugable Technologies",
"Rainforest Automation, Inc.",
"Eden Innovations",
"Shenzhen Reecam Tech.Ltd.",
"LITE-ON CLEAN ENERGY TECHNOLOGY CORP.",
"Imaging Diagnostics",
"Cheetah Hi-Tech, Inc.",
"DAEHAP HYPER-TECH",
"Visteon Corporation",
"RF IDeas",
"SAE IT-systems GmbH & Co. KG",
"Siano Mobile Silicon Ltd.",
"Shenzhen Ostar Display Electronic Co.,Ltd",
"zte corporation",
"DIGIBRAS INDUSTRIA DO BRASILS/A",
"Vertu Corporation Limited",
"DEP Company",
"CountMax,  ltd",
"KST technology",
"NIC.br- Nucleo de Informacao e Coordenacao do Ponto BR",
"ARIMA Communications Corp.",
"Actiontec Electronics, Inc",
"Shenzhen Coship Electronics Co., Ltd.",
"Litemax Electronics Inc.",
"Cisco-Linksys, LLC",
"Rosewill Inc.",
"Bekey A/S",
"Arcadia Networks Co. Ltd. ",
"NET2GRID BV",
"Private",
"Amscreen Group Ltd",
"WKK TECHNOLOGY LTD.",
"Hills Sound Vision & Lighting",
"Shenzhen CATIC Bit Communications Technology Co.,Ltd",
"Cisco Systems, Inc",
"Shandong Taixin Electronic co.,Ltd",
"Micro-Star Int'l Co, Ltd",
"LONG BEN (DONGGUAN) ELECTRONIC TECHNOLOGY CO.,LTD.",
"Mueller Systems",
"zte corporation",
"COMMSEN CO., LIMITED",
"Securifi Ltd",
"Panodic(ShenZhen) Electronics Limted",
"i3 International Inc.",
"Amphitech",
"Ruckus Wireless",
"Phillips Machine & Welding Co., Inc. ",
"Borea",
"Cisco Systems, Inc",
"Binatone Telecommunication Pvt. Ltd",
"Uros Oy",
"Kriwan Industrie-Elektronik GmbH",
"ETH Inc.",
"Vitek Industrial Video Products, Inc.",
"Shanghai TYD Elecronic Technology Co. Ltd",
"Cisco Systems, Inc",
"Omnima Limited",
"Alpinion Medical Systems",
"BEIJING HAIHEJINSHENG NETWORK TECHNOLOGY CO. LTD.",
"Data Management, Inc.",
"Shenzhen CZTIC Electronic Technology Co., Ltd  ",
"Innovation Wireless",
"Farmage Co., Ltd.",
"Seine Image Int'l Co., Ltd",
"iConnectivity",
"Fusion Transactive Ltd.",
"Jiangsu Cynray IOT Co., Ltd.",
"Yichun MyEnergy Domain, Inc",
"Chyi Lee industry Co., ltd.",
"Schneider Electric Asia Pacific Ltd",
"Taimag Corporation",
"Arrowhead Alarm Products Ltd",
"Labor S.r.L.",
"Relay2, Inc.",
"Vishal Telecommunications Pvt Ltd",
"Applied Technical Systems",
"Shenzhen Y&D Electronics Co.,LTD.",
"ADL Embedded Solutions, Inc.",
"Cisco Systems, Inc",
"NuLEDs, Inc.",
"Shina System Co., Ltd",
"Radinet Communications Inc.",
"Linea Research Ltd",
"Hangzhou I'converge Technology Co.,Ltd",
"Zen Eye Co.,Ltd",
"EnerAccess inc",
"Global Digitech Co LTD",
"NCTech Ltd",
"Syes srl",
"Triton Electronic Systems Ltd.",
"TAIYO YUDEN CO.,LTD",
"Uniqoteq Ltd.",
"OHSUNG ELECTRONICS CO., LTD.",
"Netronics Technologies Inc.",
"XOS",
"Xapt GmbH",
"Cisco Systems, Inc",
"BrightSign LLC",
"Bosch Software Innovations GmbH",
"KETRON S.R.L.",
"TRUMPF Laser GmbH + Co. KG",
"Mitsubishi Electric Corporation",
"PAD Peripheral Advanced Design Inc.",
"KYOKKO ELECTRIC Co., Ltd.",
"HTC Corporation",
"Omega Elektronik AS",
"Crenus Co.,Ltd.",
"SVA TECHNOLOGIES CO.LTD",
"Ericsson - North America",
"VIPAR GmbH",
"AXIM Communications",
"CHINA GREATWALL COMPUTER SHENZHEN CO.,LTD",
"Trex Network LLC",
"Cisco Systems, Inc",
"Nome Oy",
"Nabto",
"PSG Plastic Service GmbH",
"MikroBits",
"Fr. Sauter AG",
"Advanced Mobile Telecom co.,ltd.",
"Ubiquitous Computing Technology Corporation",
"Murata Manufacturing Co., Ltd.",
"Lintes Technology Co., Ltd.",
"VAHLE DETO GmbH",
"Yahoo! JAPAN",
"SHENZHEN DAJIAHAO TECHNOLOGY CO.,LTD",
"UniPrint",
"URadio Systems Co., Ltd",
"Hawkeye Tech Co. Ltd",
"Detlef Fink Elektronik & Softwareentwicklung",
"BEIJING GEHUA CATV NETWORK CO.,LTD",
"Bear Flag Design, Inc.",
"Xena Networks",
"Hanson Technology",
"FloDesign Wind Turbine Corporation",
"Helmut Mauell GmbH",
"SHENZHEN WEIJIU INDUSTRY AND TRADE DEVELOPMENT CO., LTD",
"Sankosha Corporation",
"Infoblox",
"Compex Systems Pte Ltd",
"TTTech Computertechnik AG",
"BLUE WAVE NETWORKING CO LTD",
"Gemtek Technology Co., Ltd.",
"PixeLINK",
"Diehl BGT Defence GmbH & Co. KG",
"RIM",
"Moog, Ing",
"Apex Tool Group GmbH & Co OHG",
"Cisco Systems, Inc",
"MobilMAX Technology Inc.",
"Obelux Oy",
"Accupix Inc.",
"Greenlee",
"TOKYO RADAR CORPORATION",
"CLOOS ELECTRONIC GMBH",
"Espotel Oy",
"Cisco Systems, Inc",
"KUHN SA",
"8Devices",
"Newtek Electronics co., Ltd.",
"Fiber Optic & telecommunication INC.",
"Philips Healthcare PCCI",
"RADMAX COMMUNICATION PRIVATE LIMITED",
"COFLEC",
"Building Block Video",
"marco Systemanalyse und Entwicklung GmbH",
"Shenzhen TG-NET Botone Technology Co.,Ltd.",
"Cisco Systems, Inc",
"Keen High Holding(HK) Ltd.",
"Kuipers Electronic Engineering BV",
"ARC Wireless LLC",
"Sub10 Systems Ltd",
"Nokia Corporation",
"Sound Masking Inc.",
"Honeywell HomMed",
"Alcatel Lucent",
"MHL, LLC",
"CDYNE Corporation",
"SAKURA Internet Inc.",
"Happyelectronics Co.,Ltd",
"HTC Corporation",
"Veros Systems, Inc.",
"Kontron Design Manufacturing Services (M) Sdn. Bhd",
"SmartOptics AS",
"bluesky",
"Tenyu Tech Co. Ltd.",
"EAGLE KINGDOM TECHNOLOGIES LIMITED",
"HCT. Co., Ltd.",
"Shenzhen Loadcom Technology Co.,Ltd",
"TechFaith Wireless Technology Limited",
"taskit GmbH",
"iota Computing, Inc.",
"Fujian Shenzhou Electronic Co.,Ltd",
"LaonPeople",
"Buwon Technology",
"SMC Networks Inc",
"B-Link Electronic Limited",
"GJsun Optical Science and Tech Co.,Ltd.",
"Adanis Inc.",
"TAIYO YUDEN CO., LTD.",
"Palo Alto Networks",
"Digistar Telecom. SA",
"HES-SO",
"Kinetic Avionics Limited",
"Actiontec Electronics, Inc",
"IEEE 1905.1",
"ALSTOM HYDRO FRANCE",
"CIAS Elettronica srl",
"Cisco Systems, Inc",
"AmTRAN Video Corporation",
"FERMAX ELECTRONICA S.A.U.",
"FUNDACION TEKNIKER",
"iKnowledge Integration Corp.",
"Foxconn(NanJing) Communication Co.,Ltd.",
"ORIENTAL PACIFIC INTERNATIONAL LIMITED",
"TECHNOSOFT INTERNATIONAL SRL",
"Cisco Systems, Inc",
"Alcomp, Inc",
"JSC Zavod im. Kozitsky",
"ESTUN AUTOMATION TECHNOLOY CO., LTD",
"vastriver Technology Co., Ltd",
"JRI-Maxant",
"PowerRay Co., Ltd.",
"M Rutty Holdings Pty. Ltd.",
"Ruckus Wireless",
"COX CO., LTD",
"8D Technologies",
"Minibar Systems",
"Concern Axion JSC",
"GoPro",
"ShenZhen EZL Technology Co., Ltd",
"Alphatronics BV",
"OpenXS BV",
"Shenzhen Wonhe Technology Co., Ltd",
"Huiyang Technology Co., Ltd",
"Neul Ltd",
"Comsis",
"Siconix Inc.",
"Private",
"Zebra Technologies Inc",
"ASKEY COMPUTER CORP",
"Cisco Systems, Inc",
"Thing-talk Wireless Communication Technologies Corporation Limited",
"ROGER D.Wensker, G.Wensker sp.j.",
"SOL INDUSTRY PTE., LTD",
"Miller Electric Mfg. Co.",
"ANDTEK",
"Rusteletech Ltd.",
"Intrepid Control Systems, Inc.",
"SEIKO EPSON CORPORATION",
"Linktop Technology Co., LTD",
"Pan Studios Co.,Ltd.",
"Observator instruments",
"FuJian Elite Power Tech CO.,LTD.",
"Worldplay (Canada) Inc.",
"EasySYNC Ltd.",
"Delta Control GmbH",
"Enterasys",
"Invoxia",
"RIM",
"3pleplay Electronics Private Limited",
"Funkwerk plettac electronic GmbH",
"VOISMART",
"Adaptive Spectrum and Signal Alignment (ASSIA), Inc.",
"SMAX Technology Co., Ltd.",
"Marini Impianti Industriali s.r.l.",
"Private",
"Eyedro Green Solutions Inc.",
"Alcatel Lucent",
"Cisco Systems, Inc",
"Cisco Systems, Inc",
"Ellips B.V.",
"Chaney Instrument Co.",
"Korea CNO Tech Co., Ltd",
"He Shan World Fair Electronics Technology Limited",
"Frontline Test Equipment",
"Beijing Beny Wave Technology Co Ltd",
"BASIC Co.,Ltd.",
"Shenzhen Gongjin Electronics Co., Ltd.",
"PentronicAB",
"Kingspan Environmental Ltd",
"Actions Semiconductor Co.,Ltd.(Cayman Islands)",
"Beijing Ding Qing Technology, Ltd.",
"Nokia Corporation",
"Nokia Corporation",
"eSSys Co.,Ltd",
"COSTEL.,CO.LTD",
"Symeo GmbH",
"FAG Industrial Services GmbH",
"Napco Security Technologies",
"Logital Co. Limited ",
"Hitachi Data Systems",
"Insigma Technology Co.,Ltd",
"SLE quality engineering GmbH & Co. KG",
"Sun Cupid Technology (HK) LTD",
"SHENZHEN MAXMADE TECHNOLOGY CO., LTD.",
"Athena Wireless Communications Inc",
"Linkwell Telesystems Pvt Ltd",
"Tri-Systems Corporation",
"ELESYS INC.",
"Genius Bytes Software Solutions GmbH",
"InfoBLOCK S.A. de C.V.",
"Xtremio Ltd.",
"Beijing National Railway Research & Design Institute  of Signal & Communication Co., Ltd.",
"Advanced Wireless Dynamics S.L.",
"Shenzhen Prayfly Technology Co.,Ltd",
"VOGTEC(H.K.) Co., Ltd",
"Westinghouse Digital",
"CAx soft GmbH",
"Precidata",
"Environics Oy",
"Fusion-io, Inc",
"Shenzhen Bitland Information Technology Co., Ltd.",
"DIGALOG GmbH",
"Lantech Communications Global, Inc.",
"FlatFrog Laboratories AB",
"Q Electronics Ltd",
"Vieworks",
"Explora Technologies Inc",
"Icon Time Systems",
"Fastec Imaging Corporation",
"Xslent Energy Technologies. LLC",
"BeNeXt B.V.",
"OAO Izhevskiy radiozavod",
"NASTEC LTD.",
"OptiLogix BV",
"Panasonic Mobile Communications Co., Ltd.",
"Shenzhen Ogemray Technology Co., Ltd.",
"SHENZHEN XDK COMMUNICATION EQUIPMENT CO.,LTD",
"MA Lighting Technology GmbH",
"Digital Payment Technologies",
"Estech Co.,Ltd",
"2C - Trifonov & Co",
"Panasonic Electric Works Automation Controls Techno Co.,Ltd.",
"Sitecom Europe BV",
"WEG",
"Onzo Ltd",
"Seohwa Telecom",
"Cisco Systems, Inc",
"Private",
"NOREGON SYSTEMS, INC",
"TERUMO CORPORATION",
"RF WINDOW CO., LTD.",
"GHT Co., Ltd.",
"COMPUTER OFFICE Co.,Ltd.",
"Cisco Systems, Inc",
"ATHENA",
"SYSCABLE Korea Inc.",
"Nanotron Technologies GmbH",
"Kingnetic Pte Ltd",
"Gigawave LTD",
"ZPM Industria e Comercio Ltda",
"Dream Ware Inc.",
"Voltaire",
"JUIN COMPANY, LIMITED",
"LabJack",
"Storagedata",
"MacroSAN Technologies Co., Ltd.",
"CONET CO., LTD.",
"Aligera Equipamentos Digitais Ltda",
"ADFweb.com s.r.l.",
"GEWISS S.P.A.",
"Shenzhen Jiuzhou Electric Co.,LTD",
"U-Raku, Inc.",
"M2M Solution S.A.S.",
"RIM",
"Innovid, Co., Ltd.",
"Gyeyoung I&T",
"ATEK Products, LLC",
"Cisco Systems, Inc",
"ORBIS TECNOLOGIA ELECTRICA S.A.",
"Zonar Systems",
"JAG Jakob AG",
"Sage Electronic Engineering LLC",
"Secure Meters (UK) Limited",
"OOO InProMedia",
"Katoudenkikougyousyo co ltd",
"IDY Corporation",
"Omniprint Inc.",
"IdaTech",
"TP Vision Belgium N.V. - innovation site Brugge",
"Sonardyne International Ltd",
"Radicom Research, Inc.",
"LEONI ",
"Thermo Fisher Scientific P.O.A.",
"LGE ",
"O-NET Communications(Shenzhen) Limited",
"Trendsetter Medical, LLC",
"Burroughs Payment Systems, Inc.",
"Cisco Systems, Inc",
"RENA GmbH Print Systeme",
"Nokia Corporation",
"HANGZHOU ZENOINTEL TECHNOLOGY CO., LTD",
"Shanghai Huaqin Telecom Technology Co.,Ltd",
"CONCH ELECTRONIC Co.,Ltd",
"Minetec Wireless Technologies",
"Beijing Boomsense Technology CO.,LTD.",
"SHL Telemedicine International Ltd.",
"Linked IP GmbH",
"Primax Electronics Ltd.",
"Suzhou Hanming Technologies Co., Ltd.",
"Raylios Technology",
"enLighted Inc",
"Black Box Corp.",
"Lee-Dickens Ltd",
"Wifly-City System Inc.",
"Beijing Risbo Network Technology Co.,Ltd",
"Accuenergy (CANADA) Inc",
"Sogecam Industrial, S.A.",
"Actifio Inc",
"SHARP Corporation",
"BodyMedia, Inc.",
"Nokia Corporation",
"Sierra Wireless Inc",
"busware.de",
"Nokia Corporation",
"Embedded Automation, Inc.",
"Wuhan Zhongyuan Huadian Science & Technology Co.,",
"Tianjin Deviser Electronics Instrument Co., Ltd",
"IntelliVoice Co.,Ltd.",
"Seagate Technology",
"Velocytech",
"UMPI Elettronica",
"Panaccess Systems GmbH",
"NEXGEN Mediatech Inc.",
"IES GmbH & Co. KG",
"Miljovakt AS",
"Alpha Security Products",
"Advanced PANMOBIL Systems GmbH & Co. KG",
"Omnibit Inc.",
"VOLANS",
"PATECH",
"airPointe of New Hampshire",
"nSTREAMS Technologies, Inc.",
"Shanghai Qihui Telecom Technology Co., LTD",
"Simm Tronic Limited ",
"Nata-Info Ltd.",
"Cisco Systems, Inc",
"Bison Electronics Inc.",
"Justone Technologies Co., Ltd.",
"Huayuan Technology CO.,LTD",
"Vodafone UK",
"Orion Diagnostica Oy",
"UTC Fire and Security",
"Beijing Newmine Technology",
"Cisco Systems, Inc",
"Intune Networks",
"Looxcie Inc.",
"Cisco Systems, Inc",
"GENIX INFOCOMM CO., LTD.",
"There Corporation Oy",
"Wuxi Keboda Electron Co.Ltd",
"Net One Partners Co.,Ltd.",
"Cisco Systems, Inc",
"BYD Precision Manufacture Company Ltd.",
"HENGBAO Corporation LTD.",
"Cyber-Rain, Inc.",
"Nokia Corporation",
"Remec Broadband Wireless , LLC",
"RaonThink Inc.",
"CLAY PAKY SPA",
"CAT SYSTEM CO.,LTD.",
"DAEYEON Control&Instrument Co,.Ltd",
"Luxcom Technologies Inc.",
"Degreane Horizon",
"Fujian Newland Auto-ID Tech. Co,.Ltd.",
"WEY Elektronik AG",
"Auto Industrial Co., Ltd.",
"HWA YAO TECHNOLOGIES CO., LTD",
"ATOCS (Shenzhen) LTD",
"H2A Systems, LLC",
"Arantia 2010 S.L.",
"Anadem Information Inc.",
"TUBITAK UEKAE",
"Resolution Audio",
"INAT GmbH",
"KE Knestel Elektronik GmbH",
"Control Technology Inc.",
"McCain Inc",
"Cisco Systems, Inc",
"Nortel Networks",
"Precor Inc",
"Ubiquitous Internet Telecom Co., Ltd",
"General Electric Consumer and Industrial",
"Display Systems Ltd",
"Chengdu Volans Technology CO.,LTD",
"Sun Fountainhead USA. Corp ",
"Quatius Limited",
"DASCOM Europe GmbH",
"Jetlun (Shenzhen) Corporation",
"MaxID (Pty) Ltd",
"MICRO-STAR INT'L CO.,LTD",
"RADSPIN",
"Shanghai B-Star Technology Co",
"VIG",
"Advanced Network Devices (dba:AND)",
"Advanced Telemetry",
"SHENZHEN MAGNUS TECHNOLOGIES CO.,LTD",
"Gradual Tecnologia Ltda.",
"NTT Communications Corporation",
"Reco S.p.A.",
"Talaris (Sweden) AB",
"Wellav Technologies Ltd",
"Bi2-Vision",
"Optcom Co., Ltd.",
"Fugoo Coorporation",
"People Power Company",
"UniComm Inc.",
"Nortel Networks",
"VideoHome Technology Corp.",
"YOKOTA INDUSTRIAL CO,.LTD",
"Racktivity",
"Dominion Voting Systems Corporation",
"Tenda Technology Co., Ltd.",
"Cisco Systems, Inc",
"Digital One Technologies, Limited",
"DigiView S.r.l.",
"Application Solutions (Electronics and Vision) Ltd",
"Pixavi AS",
"Cisco Systems, Inc",
"SmartDrive Systems Inc.",
"AMS NEVE LTD",
"U2S co.",
"TM-Research Inc.",
"Nethra Imaging Incorporated",
"Bionics Corp.",
"ALT Systems Ltd",
"Star-Net",
"ELS-GmbH & Co. KG",
"OzVision America LLC",
"Cisco Systems, Inc",
"Tigo Energy",
"Thyssenkrupp Aufzugswerke GmbH",
"I.S.E. S.r.l.",
"Iton Technology Limited",
"Shang Hai Tyd. Electon Technology Ltd.",
"Zhejiang FeiYue Digital Technology Co., Ltd",
"A. S. Thomas, Inc.",
"Delphin Technology AG",
"NEC Personal Products, Ltd",
"The Goldman Sachs Group, Inc.",
"DETRACOM",
"Most Lucky Trading Ltd",
"JayBird LLC",
"PSS Belgium N.V.",
"MOVEK ",
"A.O. Smith Water Products",
"Egker Kft.",
"PRF Co., Ltd.",
"Cisco Systems, Inc",
"Wearable Inc.",
"Create New Technology (HK) Limited Company",
"Xia Men UnionCore Technology LTD.",
"United Integrated Services Co., Led.",
"CVC",
"MIPRO Electronics Co., Ltd",
"Geenovo Technology Ltd.",
"Grainmustards, Co,ltd.",
"CE Digital(Zhenjiang)Co.,Ltd",
"Nordiag ASA",
"INCOstartec GmbH",
"SolarEdge Technologies",
"AirDio Wireless, Inc.",
"XRPLUS Inc.",
"Instrumentation Technologies d.d.",
"IKT Advanced Technologies s.r.o.",
"Geophysical Survey Systems, Inc.",
"SAE Magnetics (H.K.) Ltd.",
"ISGUS GmbH",
"Femtocomm System Technology Corp.",
"Engel Axil S.L.",
"Mercury Systems, Inc.",
"KOREA MAINTENANCE",
"Mobile Communications Korea Incorporated",
"Star Link Communication Pvt. Ltd.",
"kasercorp, ltd",
"ZillionTV Corporation",
"Cisco Systems, Inc",
"Cypress Solutions Inc",
"Manufacturing Resources International",
"TEAC Australia Pty Ltd.",
"Enabling Technology Pty Ltd",
"Tunstall Healthcare A/S",
"J&M Analytik AG",
"netTALK.com, Inc.",
"I-TEC Co., Ltd.",
"i-mate Development, Inc.",
"Private",
"Terrier SC Ltd",
"General Dynamics Robotic Systems",
"KISAN SYSTEM",
"Ajoho Enterprise Co., Ltd.",
"A-Max Technology Macao Commercial Offshore Company Limited",
"DEIF A/S",
"AUTOVISION Co., Ltd",
"ESSENSIUM NV",
"Technology Advancement Group, Inc.",
"SP Corp",
"Optical Systems Design",
"Ningbo Andy Optoelectronic Co., Ltd.",
"DEKA R&D",
"Semihalf",
"Cisco Systems, Inc",
"Proventix Systems, Inc.",
"Insightek Corp.",
"Core System Japan",
"T-Platforms (Cyprus) Limited",
"Circontrol S.A.",
"LIOS Technology GmbH"]
